"""${message}

Revision ID: 095caf5052cb
Revises: 4307bacef95e
Create Date: 2026-09-04 10:51:49.671762

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "095caf5052cb"
down_revision: str | Sequence[str] | None = "4307bacef95e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_permissions",
        sa.Column("admin_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("assigned_by", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["admins.id"],
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["admins.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
        ),
        sa.PrimaryKeyConstraint("admin_id", "permission_id"),
    )
    op.create_table(
        "otp",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("admin_id", sa.UUID(), nullable=False),
        sa.Column("hashed_otp", sa.String(), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum("VERIFICATION", "PASSWORD_RESET", name="otppurpose"),
            nullable=False,
        ),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("expires_in", sa.Integer(), nullable=False),
        sa.Column("max_retry_limit", sa.Integer(), nullable=False),
        sa.Column("current_retry_attempt", sa.Integer(), nullable=False),
        sa.Column("max_resend_limit", sa.Integer(), nullable=False),
        sa.Column("current_resend_attempt", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["admin_id"], ["admins.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_otp_admin_id"), "otp", ["admin_id"], unique=False)
    op.drop_table("roles")
    op.add_column("admins", sa.Column("username", sa.String(), nullable=False))
    op.add_column("admins", sa.Column("firstname", sa.String(), nullable=False))
    op.add_column("admins", sa.Column("lastname", sa.String(), nullable=False))
    op.add_column("admins", sa.Column("email", sa.String(), nullable=False))
    op.add_column("admins", sa.Column("hashed_password", sa.String(), nullable=False))

    authroles_enum = postgresql.ENUM("SUPER_ADMIN", "ADMIN", name="authroles")
    authroles_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "admins",
        sa.Column(
            "role",
            postgresql.ENUM(
                "SUPER_ADMIN", "ADMIN", name="authroles", create_type=False
            ),
            nullable=False,
        ),
    )

    op.add_column("admins", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column("admins", sa.Column("is_verified", sa.Boolean(), nullable=False))
    op.add_column(
        "admins", sa.Column("last_login", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "admins",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "admins",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index(op.f("ix_admins_email"), "admins", ["email"], unique=True)
    op.create_index(op.f("ix_admins_username"), "admins", ["username"], unique=True)
    op.add_column("permissions", sa.Column("name", sa.String(), nullable=False))
    op.add_column(
        "permissions",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("session", sa.Column("admin_id", sa.UUID(), nullable=False))
    op.add_column(
        "session", sa.Column("hashed_refresh_token", sa.String(), nullable=False)
    )
    op.add_column("session", sa.Column("is_used", sa.Boolean(), nullable=False))
    op.add_column("session", sa.Column("expires_in", sa.Integer(), nullable=False))
    op.add_column("session", sa.Column("user_agent", sa.String(), nullable=True))
    op.add_column("session", sa.Column("ip_address", sa.String(), nullable=True))
    op.add_column("session", sa.Column("device_type", sa.String(), nullable=True))
    op.add_column(
        "session",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "session",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index(op.f("ix_session_admin_id"), "session", ["admin_id"], unique=False)
    op.create_foreign_key(
        "fk_session_admin_id_admins",
        "session",
        "admins",
        ["admin_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_session_admin_id_admins", "session", type_="foreignkey")
    op.drop_index(op.f("ix_session_admin_id"), table_name="session")
    op.drop_column("session", "updated_at")
    op.drop_column("session", "created_at")
    op.drop_column("session", "device_type")
    op.drop_column("session", "ip_address")
    op.drop_column("session", "user_agent")
    op.drop_column("session", "expires_in")
    op.drop_column("session", "is_used")
    op.drop_column("session", "hashed_refresh_token")
    op.drop_column("session", "admin_id")
    op.drop_column("permissions", "created_at")
    op.drop_column("permissions", "name")
    op.drop_index(op.f("ix_admins_username"), table_name="admins")
    op.drop_index(op.f("ix_admins_email"), table_name="admins")
    op.drop_column("admins", "updated_at")
    op.drop_column("admins", "created_at")
    op.drop_column("admins", "last_login")
    op.drop_column("admins", "is_verified")
    op.drop_column("admins", "is_active")

    op.drop_column("admins", "role")
    postgresql.ENUM(name="authroles").drop(op.get_bind(), checkfirst=True)

    op.drop_column("admins", "hashed_password")
    op.drop_column("admins", "email")
    op.drop_column("admins", "lastname")
    op.drop_column("admins", "firstname")
    op.drop_column("admins", "username")
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("roles_pkey")),
    )
    op.drop_index(op.f("ix_otp_admin_id"), table_name="otp")
    op.drop_table("otp")
    op.drop_table("admin_permissions")
    # ### end Alembic commands ###
