"""${message}

Revision ID: 8dfd7566c7ab
Revises: f1c8babcbcc7
Create Date: 2026-09-04 14:02:26.545416

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "8dfd7566c7ab"
down_revision: str | Sequence[str] | None = "f1c8babcbcc7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
