"""${message}

Revision ID: d0d25197640a
Revises: 8dfd7566c7ab
Create Date: 2026-09-06 00:09:37.802074

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d0d25197640a"
down_revision: str | Sequence[str] | None = "8dfd7566c7ab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("session", sa.Column("expires_at", sa.Integer(), nullable=False))
    op.add_column("session", sa.Column("is_expired", sa.Boolean(), nullable=False))
    op.create_index(
        op.f("ix_session_hashed_refresh_token"),
        "session",
        ["hashed_refresh_token"],
        unique=True,
    )
    op.drop_column("session", "is_used")
    op.drop_column("session", "expires_in")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "session",
        sa.Column("expires_in", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "session",
        sa.Column("is_used", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_session_hashed_refresh_token"), table_name="session")
    op.drop_column("session", "is_expired")
    op.drop_column("session", "expires_at")
    # ### end Alembic commands ###
