"""${message}

Revision ID: f76c952abc51
Revises: 2f7f8f1c8749
Create Date: 2026-09-02 12:04:44.753848

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "f76c952abc51"
down_revision: str | Sequence[str] | None = "2f7f8f1c8749"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
