[project]
name = "backend"
version = "0.1.0"
description = "A FastAPI project scaffolded with faststrapy for mariambika project."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[all]",
    "uvicorn",
    "pydantic-settings",
    "asyncpg",
    "sqlalchemy>=2.0.52",
    "pydantic>=2.13.5",
    "alembic>=1.19.1",
    "python-dotenv>=1.2.3",
    "psycopg2>=2.9.12",
    "argon2-cffi>=25.1.0",
    "user-agents>=2.2.0",
    "pyjwt>=2.13.0",
]

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "poethepoet>=0.48.0",
    "pytest>=9.1.1",
    "ruff>=0.16.5",
]

# Custom Poe Commands
[tool.poe.tasks.dev]
cmd="uv run -m app.main"
help="Starts Fastapi development Server"

# code format
[ruff]
line-length = 79

[tool.poe.tasks.format]
cmd="ruff format ."
help="Formats code file style using Ruff"

[tool.poe.tasks.format-check]
cmd="ruff format --check ."
help="Checks the codefiles for formatting using Ruff"

# linting
[tool.poe.tasks.lint]
cmd="ruff check . --fix"
help="Runs linting on all code files in the directory."

[tool.poe.tasks.lint-check]
cmd="ruff check ."
help="Checks for linting on all code files in the directory."

# type check 
[tool.poe.tasks.typecheck]
cmd="mypy ."
help="Runs type check for related error in code files and fixes it."

[tool.poe.tasks.type-check]
cmd="mypy --check ."
help="Checks type related error in code files"

# freeze packages to requirements.txt
[tool.poe.tasks.freeze]
shell="uv pip freeze > requirements.txt"
help="Copies all the installed packages to requirements.txt file"

# alembic 
[tool.poe.tasks.alembic-init]
shell = "alembic init alembic --template async"
help="Sets up alembic for codebase"

[tool.poe.tasks.makemigration]
cmd="alembic revision --autogenerate -m '${message}'"
args=[
    { name="message", type="string", default="new migration version" }
]
help="Creates a new Alembic migration"

[tool.poe.tasks.upgrade]
cmd="alembic upgrade head"
help="Performs alembic migration to database"

# Quick Checks
[tool.poe.tasks.checks]
sequence=["format-check", "lint-check", "type-check"]
help="Checks formatting, linting, type checking all together"

# Quick styles
[tool.poe.tasks.styles]
sequence=["format", "lint", "typecheck", "freeze"]
help="Writes formatting, linting, type checking and package freezing all together"
